[package]
name = "moga"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rayon = "1.10.0"

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"

[profile.dev.package."*"]
opt-level = 1
debug = true
