max_width = 80
hard_tabs = false
tab_spaces = 2
format_code_in_doc_comments = true
comment_width = 80
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
